In [4]:
# 기본 자료형
#숫자형
a = 123
a = 12.34
a = 1 + 2j
a.real

1.0

In [5]:
a.imag

2.0

In [7]:
a.conjugate()

(1-2j)

In [10]:
abs(a)
a = 0o12
a

a = 0x12A
a

298

In [11]:
#논리형
b = True
b

True

In [18]:
# 사용 가능 연산자
a = 3
b = 4
a + b

a - b
a * b
a / b
a ** b

2 ** 3
a % b
7 % 3
a // b
7 // 3

2

In [19]:
#그룹 자료형
# 문자열 자료형

s1 = 'Hello python'

s1

'Hello World'

In [21]:
s2 = "Hello python"
s2

'Hello python'

In [24]:
s3 = '''Hello Python'''

s3

'Hello Python'

In [25]:
s4 = """Hello Python"""

s4

'Hello Python'

In [26]:
#사용 가능 연산자

head = "Python"
tail = " is fun"

head + tail

'Python is fun'

In [27]:
head *2

'PythonPython'

In [29]:
print("=" * 5)

=====


In [31]:
a = "Now is better than never"
a[0]

'N'

In [32]:
a[4]

'i'

In [33]:
a[-1]

'r'

In [34]:
a[-2]

'e'

In [35]:
b = a[0] + a[1] + a[2]
b

'Now'

In [36]:
a[0:3]

'Now'

In [37]:
a[4:6]

'is'

In [38]:
a[19:]

'never'

In [39]:
a[:3]

'Now'

In [40]:
a[:]

'Now is better than never'

In [41]:
a[7:-11]

'better'

In [42]:
a = 'Python'
a.count("p")

0

In [43]:
#그룹 자료형
# 문자열 자료형
# 사용 가능 연산자
a.find("y")

1

In [49]:
a.find('p')

-1

In [45]:
a.index("y")

1

In [47]:
b = ","
c = b.join('Abcd')
c

'A,b,c,d'

In [48]:
a.upper()

'PYTHON'

In [50]:
a.lower()

'python'

In [52]:
d = "     py       "
d.lstrip()

'py       '

In [53]:
d.rstrip()

'     py'

In [54]:
d.strip()

'py'

In [55]:
a[1] = 'y'

TypeError: 'str' object does not support item assignment

In [56]:
a = "Python is difficult"
a.replace("difficult","funny")

'Python is funny'

In [57]:
a.split()

['Python', 'is', 'difficult']

In [58]:
b = "a,b,c,d"
b

'a,b,c,d'

In [59]:
b.split(',')

['a', 'b', 'c', 'd']

In [60]:
#그룹 자료형
# 리스트 자료형
# 사용 가능 연산자

a = [1,2,3]
b = ['Life','is','too','short']
c = [1,2,'life','is']
d = [1,2,[3,4],['life','is']]
d[0]

1

In [61]:
d[2]

[3, 4]

In [62]:
d[3]

['life', 'is']

In [63]:
d[3][-1]

'is'

In [64]:
d[0:3]

[1, 2, [3, 4]]

In [65]:
a + b

[1, 2, 3, 'Life', 'is', 'too', 'short']

In [66]:
b[0] + "hi ~ ^^"

'Lifehi ~ ^^'

In [67]:
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [69]:
a[2] = 99
a

[1, 2, 99]

In [70]:
a[1:2] = ['a','b','c']
a

[1, 'a', 'b', 'c', 99]

In [72]:
a[-1] = ['d', 'e', 'f'] 
a

[1, 'a', 'b', 'c', ['d', 'e', 'f']]

In [74]:
del a[-1]
a

[1, 'a', 'b']

In [75]:
a.append(5)

In [76]:
b.sort()
b

['Life', 'is', 'short', 'too']

In [77]:
a = [3,4,1,9]
a.reverse
a

[3, 4, 1, 9]

In [78]:
a.index(9)

3

In [79]:
a.insert(0,99)
a

[99, 3, 4, 1, 9]

In [80]:
a.remove(99)
a

[3, 4, 1, 9]

In [81]:
b = [1,2,3]
b.pop()

3

In [82]:
b

[1, 2]

In [83]:
b.pop(0)

1

In [84]:
b

[2]

In [85]:
a = [2,1,0,2,3,2,4,2]
a.count(2)

4

In [86]:
# 그룹 자료형
# 튜플 자료형
# 사용 가능 연산자

t1 = (1,)
t2 = (1,2,3)
t3 = 1,2,3
t4 = (1,2,(3,4),('life','is'))
t4[0]

1

In [87]:
t4[3][-1]

'is'

In [88]:
t4[0:3]

(1, 2, (3, 4))

In [89]:
t1 + t2

(1, 1, 2, 3)

In [93]:
#t1 + "hi~ ^^;"

t2 * 3

#t2[2] = 99

(1, 2, 3, 1, 2, 3, 1, 2, 3)

In [94]:
# 그룹 자료형
# 딕셔너리 자료형
# 사용 가능 연산자

dic = {'name':'Hong','phone':'01012345678','birth':'0814'}
dic[1] = 'a'
dic

{'name': 'Hong', 'phone': '01012345678', 'birth': '0814', 1: 'a'}

In [95]:
dic['pet'] = 'dog'
dic

{'name': 'Hong', 'phone': '01012345678', 'birth': '0814', 1: 'a', 'pet': 'dog'}

In [96]:
del dic[1]
dic

{'name': 'Hong', 'phone': '01012345678', 'birth': '0814', 'pet': 'dog'}

In [97]:
dic['pet']

'dog'

In [98]:
dic['name']

'Hong'

In [99]:
dic.keys()

dict_keys(['name', 'phone', 'birth', 'pet'])

In [100]:
list(dic.keys())

['name', 'phone', 'birth', 'pet']

In [101]:
dic.values()

dict_values(['Hong', '01012345678', '0814', 'dog'])

In [102]:
list(dic.values())

['Hong', '01012345678', '0814', 'dog']

In [103]:
dic.items()

dict_items([('name', 'Hong'), ('phone', '01012345678'), ('birth', '0814'), ('pet', 'dog')])

In [105]:
dic.clear()
dic

{}

In [106]:
s1 = {1,2,'a',5}
s2 = set([1,2,3,4,5,6])
s2

{1, 2, 3, 4, 5, 6}

In [107]:
s3 = set([4,5,6,7,8,9])
s3

{4, 5, 6, 7, 8, 9}

In [108]:
s2 & s3

{4, 5, 6}

In [109]:
s2.intersection(s3)

{4, 5, 6}

In [110]:
s2 | s3

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [111]:
s2.union(s3)

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [112]:
s2 - s3

{1, 2, 3}

In [113]:
s2.difference(s3)

{1, 2, 3}

In [114]:
s3.difference(s2)

{7, 8, 9}

In [115]:
s2.add(7)
s2

{1, 2, 3, 4, 5, 6, 7}

In [116]:
s2.update([6,7,8,9,10])
s2

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [117]:
s2.remove(7)
s2

{1, 2, 3, 4, 5, 6, 8, 9, 10}

In [118]:
# 조건문
# 조건식

# 사용 가능 연산자

x = 3
y = 2
x == y

False

In [119]:
x != y

True

In [120]:
x > y

True

In [121]:
money = 1300

In [122]:
if money >= 1200 and money < 3500:
    print("버스를 탈 수 있습니다.")



버스를 탈 수 있습니다.


In [123]:
1 in [1,2,3]

True

In [124]:
x in [1,2,3]

True

In [125]:
x not in [1,2,3]

False

In [126]:
'a' in ('a','b','c','d')

True

In [127]:
'i' not in 'Python'

True

In [128]:
if money < 10:
    pass
else:
    print("저금하자!")

    

저금하자!


In [129]:
#반복문
# for문
test_list = ['one','two','three']
for i in test_list:
    x = i + '!'
    print(x)

    

one!
two!
three!


In [130]:
number = 0
for score in [90, 25, 67, 45, 93]:
    number += 1
    if score >= 60:
        print("%d번 학생은 합격입니다." %number)
    else:
        print("%d번 학생은 불합격입니다." %number)

        

1번 학생은 합격입니다.
2번 학생은 불합격입니다.
3번 학생은 합격입니다.
4번 학생은 불합격입니다.
5번 학생은 합격입니다.


In [131]:
# while 문
i = 0
while i < 5:
    i += 1
    print('*'*i)

    

*
**
***
****
*****


In [132]:
def sum1(a,b):
    x = a + b
    return x

def sum2(*args):
    x = 0
    for i in args:
        x += i
    return x


In [133]:
a = 5
b = 3

In [134]:
sum1(a,b)

8

In [135]:
sum1(3,5)

8

In [136]:
sum2(1,2,3,4,5)

15

In [137]:
sum2(2,3.5,10)

15.5

In [140]:
# 내장 함수
# 함수 종류
abs(-3.5)
all([1,2,3,4])
all([4,-2,0.0,4])
any([1,2,3,4])
any([4,-2,0.0,4])
chr(97)
chr(48)
ord('a')
ord('0')

48

In [141]:
dir([1,2,3])
dir({'1':'a'})
dir(1)
divmod(7,3)

(2, 1)

In [142]:
divmod(1.3, 0.2)

(6.0, 0.09999999999999998)

In [143]:
oct(8)

'0o10'

In [144]:
oct(234)

'0o352'

In [145]:
hex(16)

'0x10'

In [146]:
hex(234)

'0xea'

In [147]:
a = 3
id(a)

4367751392

In [148]:
int('3')

3

In [149]:
str(3)

'3'

In [150]:
list("Python")

['P', 'y', 't', 'h', 'o', 'n']

In [151]:
list((1,2,3))

[1, 2, 3]

In [158]:
# 모듈과 패키지
# 파이썬 코드
# Request("http://www.hanb.co.kr")

import urllib.request
urllib.request.Request('http://www.hanb.co.kr')

In [161]:
import pandas
pandas.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [162]:
from datetime import datetime
datetime.now()

datetime.datetime(2024, 3, 28, 0, 29, 23, 625033)

In [163]:
import numpy as np
np.__version__

'1.26.4'

In [164]:
ar1 = np.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [165]:
type(ar1)

numpy.ndarray

In [166]:
ar2 = np.array([[10,20,30],[40,50,60]])
ar2

array([[10, 20, 30],
       [40, 50, 60]])

In [167]:
ar3 = np.arange(1,11,2)
ar3

array([1, 3, 5, 7, 9])

In [169]:
ar4 = np.array([1, 2, 3, 4, 5, 6]).reshape((3, 2))
ar4

array([[1, 2],
       [3, 4],
       [5, 6]])

In [171]:
ar5 = np.zeros((2,3))
ar5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [172]:
ar6 =  ar2[0:2,0:2]
ar6

array([[10, 20],
       [40, 50]])

In [173]:
ar7 = ar2[0,:]
ar7

array([10, 20, 30])

In [174]:
ar8 = ar1 + 10
ar8

array([11, 12, 13, 14, 15])

In [175]:
ar1 + ar8

array([12, 14, 16, 18, 20])

In [176]:
ar8 - ar1

array([10, 10, 10, 10, 10])

In [177]:
ar1 * 2

array([ 2,  4,  6,  8, 10])

In [178]:
ar9 = np.dot(ar2,ar4)
ar9

array([[220, 280],
       [490, 640]])

In [179]:
# pandas
# Series 자료형

import pandas as pd
pd.__version__

'2.2.1'

In [180]:
data1 = [10,20,30,40,50]
data1

[10, 20, 30, 40, 50]

In [181]:
data2 = ['1반','2반','3반','4반','5반']
data2

['1반', '2반', '3반', '4반', '5반']

In [182]:
sr1 = pd.Series(data1)
sr1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [183]:
sr2 = pd.Series(data2)
sr2

0    1반
1    2반
2    3반
3    4반
4    5반
dtype: object

In [184]:
sr3 = pd.Series([101,102,103,104,105])
sr3

0    101
1    102
2    103
3    104
4    105
dtype: int64

In [185]:
sr4 = pd.Series(['월', '화', '수', '목', '금'])
sr4

0    월
1    화
2    수
3    목
4    금
dtype: object

In [186]:
sr5 = pd.Series(data1, index = [1000, 1001, 1002, 1003, 1004])
sr5

1000    10
1001    20
1002    30
1003    40
1004    50
dtype: int64

In [187]:
sr6 = pd.Series(data1, index=data2)
sr6

1반    10
2반    20
3반    30
4반    40
5반    50
dtype: int64

In [188]:
sr7 = pd.Series(data2, index= data1)
sr7

10    1반
20    2반
30    3반
40    4반
50    5반
dtype: object

In [189]:
sr8 = pd.Series(data2, index = sr4)
sr8

월    1반
화    2반
수    3반
목    4반
금    5반
dtype: object

In [190]:
sr8[2]

/var/folders/m5/z71192pd5msbtxhv764jq3_h0000gn/T/ipykernel_14870/1842568196.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sr8[2]


'3반'

In [191]:
sr8['수']


'3반'

In [192]:
sr8[-1]

/var/folders/m5/z71192pd5msbtxhv764jq3_h0000gn/T/ipykernel_14870/609848320.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sr8[-1]


'5반'

In [193]:
sr8[0:4]

월    1반
화    2반
수    3반
목    4반
dtype: object

In [194]:
sr8.values

array(['1반', '2반', '3반', '4반', '5반'], dtype=object)

In [197]:
sr1 + sr3

0    111
1    122
2    133
3    144
4    155
dtype: int64

In [196]:
sr4 + sr2

0    월1반
1    화2반
2    수3반
3    목4반
4    금5반
dtype: object

In [198]:
#Pandas
#DataFrame 자료형

data_dic ={
    'year':[2018,2019,2020],
    'sales':[350, 480, 1099]
}

data_dic

{'year': [2018, 2019, 2020], 'sales': [350, 480, 1099]}

In [199]:
df1 = pd.DataFrame(data_dic)

df1

year  sales
0  2018    350
1  2019    480
2  2020   1099

In [200]:
df2 = pd.DataFrame([[89.2, 92.5, 90.8], [92.8, 89.9, 95.2]],
index = ['중간고사', '기말고사'], columns = data2[0:3])

df2

1반    2반    3반
중간고사  89.2  92.5  90.8
기말고사  92.8  89.9  95.2

In [201]:
data_df = [['20201101', 'Hong', '90', '95'], ['20201102',
'Kim', '93', '94'], ['20201103', 'Lee', '87', '97']]
df3 = pd.DataFrame(data_df)
df3

0     1   2   3
0  20201101  Hong  90  95
1  20201102   Kim  93  94
2  20201103   Lee  87  97

In [202]:
df3.columns = ['학번','이름','중간고사','기말고사']
df3

학번    이름 중간고사 기말고사
0  20201101  Hong   90   95
1  20201102   Kim   93   94
2  20201103   Lee   87   97

In [203]:
df3.head(2)

학번    이름 중간고사 기말고사
0  20201101  Hong   90   95
1  20201102   Kim   93   94

In [204]:
df3.tail(2)

학번   이름 중간고사 기말고사
1  20201102  Kim   93   94
2  20201103  Lee   87   97

In [205]:
df3['이름']

0    Hong
1     Kim
2     Lee
Name: 이름, dtype: object

In [206]:
# pandas
# DataFrame 자료형
df5 = [10,30,20,40]
df6 = ['a','g','h','c']
pd.DataFrame([df5,df6])

0   1   2   3
0  10  30  20  40
1   a   g   h   c

In [207]:
pd.DataFrame(zip(df5,df6))

0  1
0  10  a
1  30  g
2  20  h
3  40  c

In [208]:
pd.DataFrame(zip(df5, df6), index = pd.Index(['aaa', 'bbb', 'ccc', 'ddd']), columns = ['col1', 'col2'])

col1 col2
aaa    10    a
bbb    30    g
ccc    20    h
ddd    40    c

In [209]:
df7 = {'col1':[123,456,789],'col2':['aaa','bbb','cccd']}
pd.DataFrame(df7)

col1  col2
0   123   aaa
1   456   bbb
2   789  cccd